---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: simulation-deployment
  labels:
    app: simulation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: stockcharts/simulation:0.1.0
        ports:
        - containerPort: 8081
        imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: simulation-service
spec:
  type: LoadBalancer
  selector:
    app: simulation
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30300
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: extractor-deployment
  labels:
    app: extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
      - name: extractor
        image: stockcharts/extractor:0.1.0
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: stockcharts/ui:0.1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: SIMULATION_APP_HOST
          value: "192.168.99.100"
        - name: SIMULATION_APP_PORT
          value: "30300"
---
kind: Service
apiVersion: v1
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30301
