apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: simulation-deployment
  labels:
    app: simulation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: stockcharts/simulation:0.1.2
        ports:
        - containerPort: 8081
        env:
        - name: KAFKA_SERVICE
          value: "kafka-service"
---
kind: Service
apiVersion: v1
metadata:
  name: simulation-service
spec:
  type: LoadBalancer
  selector:
    app: simulation
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
