apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: stockcharts/ui:0.1.2
        ports:
        - containerPort: 8080
        env:
        - name: SIMULATION_HOST
          value: "external_ip"
        - name: SIMULATION_PORT
          value: "external_port"
---
kind: Service
apiVersion: v1
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
